$(document).ready(function(){
  $('.navbar-toggle').on('click',function(){
    $('.icon-bar-1').toggleClass('icon-bar-1-active');
    $('.icon-bar-2').toggleClass('icon-bar-2-active');
    $('.icon-bar-3').toggleClass('icon-bar-3-active');
  });
  $('#level-1-item-1').on('click',function(){
  	$('#level-1').addClass('disable');
  	$('#level-2-1').addClass('active');
  	$('#level-2-1').removeClass('disable');
  })
  $('#level-1-item-2').on('click',function(){
  	$('#level-1').addClass('disable');
  	$('#level-2-2').addClass('active');
  	$('#level-2-2').removeClass('disable');
  })
  $('#level-1-item-3').on('click',function(){
  	$('#level-1').addClass('disable');
  	$('#level-2-3').addClass('active');
  	$('#level-2-3').removeClass('disable');
  })
  $('#level-2-3-item-1').on('click',function(){
  	$('#level-2-3').addClass('disable');
  	$('#level-3-4').addClass('active');
  	$('#level-3-4').removeClass('disable');
  })
  $('#level-2-3-item-2').on('click',function(){
  	$('#level-2-3').addClass('disable');
  	$('#level-3-5').addClass('active');
  	$('#level-3-5').removeClass('disable');
  })
  $('#level-2-3-item-3').on('click',function(){
  	$('#level-2-3').addClass('disable');
  	$('#level-3-6').addClass('active');
  	$('#level-3-6').removeClass('disable');
  })
  $('#level-2-1-item-1').on('click',function(){
  	$('#level-2-1').addClass('disable');
  	$('#level-3-1').addClass('active');
  	$('#level-3-1').removeClass('disable');
  	$('#level-4-7').addClass('disable');
  })
  $('#level-2-2-item-1').on('click',function(){
  	$('#level-2-2').addClass('disable');
  	$('#level-3-2').addClass('active');
  	$('#level-3-2').removeClass('disable');
  })
  $('#level-2-2-item-2').on('click',function(){
  	$('#level-2-2').addClass('disable');
  	$('#level-3-3').addClass('active');
  	$('#level-3-3').removeClass('disable');
  })
  $('#level-3-2-item-1').on('click',function(){
  	$('#level-3-2').addClass('disable');
  	$('#level-2-1').addClass('active');
  	$('#level-2-1').removeClass('disable');
  	$('#level-4-7').addClass('active');
  	$('#level-4-7').removeClass('disable');
  })
  $('#level-3-1-item-1').on('click',function(){
  	$('#level-3-1').addClass('disable');
  	$('#level-4-1').addClass('active');
  	$('#level-4-1').removeClass('disable');
  })
  $('#level-3-1-item-2').on('click',function(){
  	$('#level-3-1').addClass('disable');
  	$('#level-4-2').addClass('active');
  	$('#level-4-2').removeClass('disable');
  })
  $('#level-3-1-item-3').on('click',function(){
  	$('#level-3-1').addClass('disable');
  	$('#level-4-3').addClass('active');
  	$('#level-4-3').removeClass('disable');
  })
  $('#level-3-1-item-4').on('click',function(){
  	$('#level-3-1').addClass('disable');
  	$('#level-4-4').addClass('active');
  	$('#level-4-4').removeClass('disable');
  })
  $('#level-3-1-item-5').on('click',function(){
  	$('#level-3-1').addClass('disable');
  	$('#level-4-5').addClass('active');
  	$('#level-4-5').removeClass('disable');
  })
  $('#level-3-1-item-6').on('click',function(){
  	$('#level-3-1').addClass('disable');
  	$('#level-4-6').addClass('active');
  	$('#level-4-6').removeClass('disable');
  })
  $('#level-3-2-item-2').on('click',function(){
  	$('#level-3-2').addClass('disable');
  	$('#level-4-8').addClass('active');
  	$('#level-4-8').removeClass('disable');
  })
  $('#level-3-3-item-1').on('click',function(){
  	$('#level-3-3').addClass('disable');
  	$('#level-4-9').addClass('active');
  	$('#level-4-9').removeClass('disable');
  })
  $('#level-3-3-item-2').on('click',function(){
  	$('#level-3-3').addClass('disable');
  	$('#level-4-10').addClass('active');
  	$('#level-4-10').removeClass('disable');
  })
  $('#level-3-4-item-1').on('click',function(){
  	$('#level-3-4').addClass('disable');
  	$('#level-4-11').addClass('active');
  	$('#level-4-11').removeClass('disable');
  })
  $('#level-3-6-item-1').on('click',function(){
  	$('#level-3-6').addClass('disable');
  	$('#level-4-12').addClass('active');
  	$('#level-4-12').removeClass('disable');
  })
  $('#level-4-2-item-1').on('click',function(){
  	$('#level-4-2').addClass('disable');
  	$('#level-5-1').addClass('active');
  	$('#level-5-1').removeClass('disable');
  })
  $('#level-4-3-item-1').on('click',function(){
  	$('#level-4-3').addClass('disable');
  	$('#level-5-2').addClass('active');
  	$('#level-5-2').removeClass('disable');
  })
  $('#level-4-6-item-1').on('click',function(){
  	$('#level-4-6').addClass('disable');
  	$('#level-5-3').addClass('active');
  	$('#level-5-3').removeClass('disable');
  })
  $('#level-4-6-item-2').on('click',function(){
  	$('#level-4-6').addClass('disable');
  	$('#level-5-4').addClass('active');
  	$('#level-5-4').removeClass('disable');
  })
  $('#level-4-7-item-1').on('click',function(){
  	$('#level-4-7').addClass('disable');
  	$('#level-5-5').addClass('active');
  	$('#level-5-5').removeClass('disable');
  	$('#level-2-1').removeClass('active');
  	$('#level-2-1').addClass('disable');
  })
  $('#level-4-9-item-1').on('click',function(){
  	$('#level-4-9').addClass('disable');
  	$('#level-5-6').addClass('active');
  	$('#level-5-6').removeClass('disable');
  })
  $('#level-4-9-item-2').on('click',function(){
  	$('#level-4-9').addClass('disable');
  	$('#level-5-7').addClass('active');
  	$('#level-5-7').removeClass('disable');
  })
  $('#level-4-11-item-1').on('click',function(){
  	$('#level-4-11').addClass('disable');
  	$('#level-5-8').addClass('active');
  	$('#level-5-8').removeClass('disable');
  })
  $('#level-5-2-item-1').on('click',function(){
  	$('#level-5-2').addClass('disable');
  	$('#level-6-1').addClass('active');
  	$('#level-6-1').removeClass('disable');
  })
  $('#level-5-2-item-2').on('click',function(){
  	$('#level-5-2').addClass('disable');
  	$('#level-6-2').addClass('active');
  	$('#level-6-2').removeClass('disable');
  })
  $('#level-5-2-item-3').on('click',function(){
  	$('#level-5-2').addClass('disable');
  	$('#level-6-3').addClass('active');
  	$('#level-6-3').removeClass('disable');
  })
  $('#level-5-2-item-4').on('click',function(){
  	$('#level-5-2').addClass('disable');
  	$('#level-6-4').addClass('active');
  	$('#level-6-4').removeClass('disable');
  })
  $('#level-5-2-item-5').on('click',function(){
  	$('#level-5-2').addClass('disable');
  	$('#level-6-5').addClass('active');
  	$('#level-6-5').removeClass('disable');
  })
  $('#level-5-7-item-1').on('click',function(){
  	$('#level-5-7').addClass('disable');
  	$('#level-6-6').addClass('active');
  	$('#level-6-6').removeClass('disable');
  })
  $('#level-5-7-item-2').on('click',function(){
  	$('#level-5-7').addClass('disable');
  	$('#level-6-7').addClass('active');
  	$('#level-6-7').removeClass('disable');
  })
  $('#level-5-7-item-3').on('click',function(){
  	$('#level-5-7').addClass('disable');
  	$('#level-6-8').addClass('active');
  	$('#level-6-8').removeClass('disable');
  })
  $('#level-5-7-item-4').on('click',function(){
  	$('#level-5-7').addClass('disable');
  	$('#level-6-9').addClass('active');
  	$('#level-6-9').removeClass('disable');
  })
  $('#level-5-7-item-5').on('click',function(){
  	$('#level-5-7').addClass('disable');
  	$('#level-6-10').addClass('active');
  	$('#level-6-10').removeClass('disable');
  })
  $('#level-5-7-item-6').on('click',function(){
  	$('#level-5-7').addClass('disable');
  	$('#level-6-11').addClass('active');
  	$('#level-6-11').removeClass('disable');
  })
  $('#level-6-9-item-1').on('click',function(){
  	$('#level-6-9').addClass('disable');
  	$('#level-7-2').addClass('active');
  	$('#level-7-2').removeClass('disable');
  })
  $('#level-6-9-item-2').on('click',function(){
  	$('#level-6-9').addClass('disable');
  	$('#level-7-3').addClass('active');
  	$('#level-7-3').removeClass('disable');
  })
  $('#level-6-10-item-1').on('click',function(){
  	$('#level-6-10').addClass('disable');
  	$('#level-7-4').addClass('active');
  	$('#level-7-4').removeClass('disable');
  })
  $('#level-6-7-item-1').on('click',function(){
  	$('#level-6-7').addClass('disable');
  	$('#level-7-1').addClass('active');
  	$('#level-7-1').removeClass('disable');
  })
  $('#level-7-1-item-1').on('click',function(){
  	$('#level-7-1').addClass('disable');
  	$('#level-8-1').addClass('active');
  	$('#level-8-1').removeClass('disable');
  })
  $('#level-7-1-item-2').on('click',function(){
  	$('#level-7-1').addClass('disable');
  	$('#level-8-2').addClass('active');
  	$('#level-8-2').removeClass('disable');
  })
  $('#level-7-1-item-3').on('click',function(){
  	$('#level-7-1').addClass('disable');
  	$('#level-8-3').addClass('active');
  	$('#level-8-3').removeClass('disable');
  })
  $('#level-7-3-item-1').on('click',function(){
  	$('#level-7-3').addClass('disable');
  	$('#level-8-4').addClass('active');
  	$('#level-8-4').removeClass('disable');
  })
  $('#level-7-3-item-2').on('click',function(){
  	$('#level-7-3').addClass('disable');
  	$('#level-8-5').addClass('active');
  	$('#level-8-5').removeClass('disable');
  })
  $('#level-1-item-4').click(function(){
    $('#level-1').addClass('disable');
  	$('#level-3-7').addClass('active');
  	$('#level-3-7').removeClass('disable');
  });
  $('#level-3-7-item-1').click(function(){
    $('#level-3-7').addClass('disable');
  	$('#level-4-13').addClass('active');
  	$('#level-4-13').removeClass('disable');
  });
  $('#level-3-7-item-2').click(function(){
    $('#level-3-7').addClass('disable');
  	$('#level-4-14').addClass('active');
  	$('#level-4-14').removeClass('disable');
  });
  $('#level-4-14-item-1').click(function(){
    $('#level-4-14').addClass('disable');
  	$('#level-5-9').addClass('active');
  	$('#level-5-9').removeClass('disable');
  });
  $('#level-4-14-item-2').click(function(){
    $('#level-4-14').addClass('disable');
  	$('#level-5-10').addClass('active');
  	$('#level-5-10').removeClass('disable');
  });
  $('.about-btn').on('click',function(){
    $('.modal-window').addClass('modal-window-active');
  });
  $('.close-btn').on('click',function(){
    $('.modal-window').removeClass('modal-window-active');
  });
  $('.return-btn').on('click', function(){
    $('#level-1').addClass('active');
    $('#level-1').removeClass('disable');
    $('#level-1').siblings().addClass('disable');
  });
});